/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Account aanmaken
         * @description De rol volgt uit de code. Een code die met `DOC-` begint geeft een docent,
         *     een code die met `STU-` begint een leerling.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Account aangemaakt */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RegisterResponse"];
                    };
                };
                /** @description Ontbrekende velden ("Alle velden zijn verplicht.") of ongeldige code ("Ongeldige code.") */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Opslaan mislukt */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inloggen en JWT ophalen */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Ingelogd */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Naam of wachtwoord ontbreekt, of verkeerd wachtwoord van een docent */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Verkeerd wachtwoord van een leerling */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Gebruiker niet gevonden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Wie ben ik? (token controleren) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description De ingelogde gebruiker */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user: components["schemas"]["User"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leesprofiel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eigen leesprofiel ophalen */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Het leesprofiel */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Leesprofiel"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Nog geen leesprofiel ingevuld ("geen profiel gevonden") */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /** Leesprofiel bewerken */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LeesprofielInput"];
                };
            };
            responses: {
                /** @description Het bijgewerkte profiel. Is er nog geen profiel, dan is het antwoord leeg. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Leesprofiel"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        /**
         * Leesprofiel opslaan
         * @description Controleert dat genre, niveau, lengte en leesdoel zijn ingevuld.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LeesprofielInput"];
                };
            };
            responses: {
                /** @description Opgeslagen */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"];
                    };
                };
                /** @description Genre vergeten ("genre vergeten") of niet alle velden ingevuld */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/advies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Leesadvies genereren
         * @description Maakt op basis van het leesprofiel een advies van maximaal drie boeken.
         *     Een eerder advies van deze leerling wordt vervangen. Boeken die op thema matchen
         *     komen eerst, daarna volgen boeken die alleen op niveau passen.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Het advies */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            advies: components["schemas"]["AdviesItem"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Geen leesprofiel gevonden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leeslijst": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Eigen leeslijst ophalen */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description De leeslijst */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            books: components["schemas"]["LeeslijstItem"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        /**
         * Boek aan de eigen leeslijst toevoegen
         * @description Alleen het veld `_id` van het boek wordt gebruikt. Je mag het hele boek uit de
         *     catalogus meesturen.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LeeslijstAddRequest"];
                };
            };
            responses: {
                /** @description Boek toegevoegd */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"];
                    };
                };
                /** @description Het boek heeft geen `_id` */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Boek staat al in de leeslijst */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leeslijst/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id van het leeslijst-item */
                id: components["parameters"]["LeeslijstId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Boek uit de leeslijst verwijderen */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id van het leeslijst-item */
                    id: components["parameters"]["LeeslijstId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Verwijderd */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        options?: never;
        head?: never;
        /** Boek als gelezen of ongelezen markeren */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id van het leeslijst-item */
                    id: components["parameters"]["LeeslijstId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        gelezen: boolean;
                    };
                };
            };
            responses: {
                /** @description Bijgewerkt */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        trace?: never;
    };
    "/docenten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alle docenten om uit te kiezen (alleen leerlingen)
         * @description Geeft alleen id en naam. Wachtwoord en registratiecode worden nooit teruggegeven.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lijst met docenten, op naam gesorteerd */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            docenten: components["schemas"]["Teacher"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student/docent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Docent van de ingelogde leerling */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description De gekoppelde docent, of null */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            docent: components["schemas"]["Teacher"] | null;
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        /**
         * Docent kiezen of wijzigen
         * @description Vervangt een eerdere koppeling in één transactie. Een leerling heeft één docent.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 13 */
                        teacherId: number;
                    };
                };
            };
            responses: {
                /** @description Gekoppeld */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            teacher: components["schemas"]["Teacher"];
                        };
                    };
                };
                /** @description Ongeldige docent */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
                /** @description Docent niet gevonden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docent/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Leerlingen van de ingelogde docent */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Gekoppelde leerlingen */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            students: components["schemas"]["StudentSummary"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docent/leeslijst/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id van de leerling */
                studentId: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        /** Leeslijst van een gekoppelde leerling */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id van de leerling */
                    studentId: components["parameters"]["StudentId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description De leeslijst van de leerling */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            books: components["schemas"]["LeeslijstItem"][];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Geen docent, of de leerling is niet aan deze docent gekoppeld */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/docent/leeslijst/{studentId}/add": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Id van de leerling */
                studentId: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Boek toevoegen aan de leeslijst van een gekoppelde leerling */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Id van de leerling */
                    studentId: components["parameters"]["StudentId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Het id (`_id`) van het boek in de catalogus */
                        bookId: string;
                    };
                };
            };
            responses: {
                /** @description Boek toegevoegd */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Success"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                /** @description Geen docent, of de leerling is niet aan deze docent gekoppeld */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Boek staat al in de leeslijst ("Boek staat al in leeslijst") */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalogus doorzoeken (met paginering) */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    /** @example F2 */
                    niveau?: string;
                    /** @example Boek */
                    type?: string;
                    thema?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Een pagina met maximaal 6 boeken */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CatalogPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example Naam of wachtwoord klopt niet. */
            error: string;
            /** @description Komt bij sommige antwoorden mee en is gelijk aan de HTTP-status */
            status?: number;
        };
        Success: {
            /** @example true */
            success: boolean;
        };
        /** @enum {string} */
        Role: "teacher" | "student";
        User: {
            /** @example 3 */
            id: number;
            /** @example BasStudent2 */
            name: string;
            role: components["schemas"]["Role"];
        };
        RegisterRequest: {
            name: string;
            /** Format: password */
            password: string;
            /**
             * @description Begint met DOC- voor een docent of STU- voor een leerling
             * @example STU-123
             */
            code: string;
        };
        RegisterResponse: {
            /** @example true */
            success: boolean;
            role: components["schemas"]["Role"];
        };
        LoginRequest: {
            name: string;
            /** Format: password */
            password: string;
        };
        LoginResponse: {
            /** @description JWT, 2 uur geldig */
            token: string;
            role: components["schemas"]["Role"];
            id: number;
            name: string;
        };
        Teacher: {
            /** @example 13 */
            id: number;
            /** @example BasD */
            name: string;
        };
        /** @description Velden zijn null als de koppeling naar een verwijderde leerling wijst */
        StudentSummary: {
            id?: number | null;
            name?: string | null;
            code?: string | null;
        };
        /** @description Een boek zoals de API het teruggeeft in advies en leeslijst */
        Book: {
            Titel?: string;
            Auteur?: string;
            type?: string;
            niveau?: string;
            /** @description Thema's gescheiden door puntkomma's */
            thema?: string;
            beschrijving?: string;
        };
        CatalogBook: components["schemas"]["Book"] & {
            /** @description Id van het boek in de catalogus */
            _id: string;
        };
        CatalogPage: {
            page: number;
            /** @example 6 */
            limit: number;
            total: number;
            books: components["schemas"]["CatalogBook"][];
        };
        LeesprofielInput: {
            /**
             * @example [
             *       "historisch",
             *       "avontuur"
             *     ]
             */
            genre: string[];
            /**
             * @example [
             *       "WOII",
             *       "detective"
             *     ]
             */
            onderwerp: string[];
            /** @enum {string} */
            niveau: "F2" | "F2-F3" | "F3" | "F3+";
            /** @enum {string} */
            lengte: "kort" | "gemiddeld" | "lang";
            leesdoel: string;
        };
        Leesprofiel: components["schemas"]["LeesprofielInput"] & {
            readonly id: number;
            readonly studentId: string;
        };
        AdviesItem: {
            bookId: string;
            book: components["schemas"]["Book"] | null;
            /** @description Waarom dit boek bij het profiel past */
            reason: string;
        };
        LeeslijstAddRequest: {
            /** @description Id van het boek in de catalogus */
            _id: string;
        } & {
            [key: string]: unknown;
        };
        LeeslijstItem: {
            id: number;
            studentId: string;
            bookId: string;
            gelezen?: boolean | null;
            book?: components["schemas"]["Book"] | null;
        };
    };
    responses: {
        /** @description Token ontbreekt, is ongeldig of verlopen */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Deze rol heeft geen toegang tot deze route */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Id van het leeslijst-item */
        LeeslijstId: number;
        /** @description Id van de leerling */
        StudentId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
